<a href="https://colab.research.google.com/github/Shivam-vachhani/PyTorch-Projects/blob/main/Nural_Network_From_Scrach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df = df.drop(columns=['id','Unnamed: 32'])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [ ]:
df.shape

(569, 31)

# Train Test Split

In [ ]:
X =df.drop(columns=['diagnosis'])
y = df['diagnosis']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.92488008, -1.60366819, -0.95149109, ..., -1.2580974 ,
        -1.22524798, -0.92157846],
       [-1.21718441,  0.01751193, -1.16463232, ..., -0.25771489,
        -0.44304155,  0.06591684],
       [ 0.20871798, -1.01038525,  0.17006711, ...,  0.00493321,
        -0.33526363, -0.05010183],
       ...,
       [ 2.28650994,  0.07959968,  2.48423059, ...,  2.69551195,
         1.89704574,  0.7604249 ],
       [ 0.01931382,  0.55100666,  0.05425627, ...,  0.46277418,
         1.13933429,  0.94808644],
       [ 0.58187246, -0.12735949,  0.67725289, ...,  0.89772309,
        -0.20135773,  1.21006407]])

#Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


# Numpy Arrays to Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_test_tensor.shape

torch.Size([114])

In [ ]:
X_train.shape

(455, 30)

# Making Nural Network

In [ ]:
class NuralNetwork():

  def __init__(self,X,layer_size=[4,4,4,1]):

    input_features = X.shape[1]
    self.layer_sizes = [input_features] + layer_size

    self.weights = []
    self.bias = []

    for i in range(len(self.layer_sizes) - 1):
      self.weights.append(torch.rand(self.layer_sizes[i+1], self.layer_sizes[i], dtype=torch.float64, requires_grad=True))
      self.bias.append(torch.zeros(self.layer_sizes[i+1], dtype=torch.float64, requires_grad=True))

  def forward(self, X):
    current_input = X

    for i in range(len(self.weights)):
      output_values = torch.matmul(current_input,self.weights[i].T)+ self.bias[i]
      current_input = torch.sigmoid(output_values)
    return current_input


  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y * torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
    print(loss)
    return loss




In [ ]:

model = NuralNetwork(X_train_tensor)
epochs = 50
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  loss = model.loss_function(y_pred,y_train_tensor)
  loss.backward()
  with torch.no_grad():
    for i in range(len(model.weights)):
      model.weights[i] -= 0.1 * model.weights[i].grad
      model.bias[i] -= 0.1 * model.bias[i].grad

      model.weights[i].grad.zero_()
      model.bias[i].grad.zero_()

print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

tensor(1.1070, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(1.0404, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.9819, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.9312, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8877, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8506, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8192, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7929, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7709, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7526, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7374, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7248, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7144, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7059, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6988, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6930, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6882, dtype=torch.float64, grad

In [ ]:
model.bias

[tensor([-0.0009, -0.0003, -0.0004, -0.0006], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.0073, -0.0111, -0.0052, -0.0121], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.0065, -0.0187, -0.0492, -0.0030], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.5162], dtype=torch.float64, requires_grad=True)]

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6666666865348816
